apiVersion : apps/v1
kind: Deployment
metadata:
  name: azurekeyvaulttestapi123 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurekeyvaulttestapi123
  template:
    metadata:
      labels:
        app: azurekeyvaulttestapi123 
    spec:
      containers:
        - name: azurekeyvaulttestapi123 
          image: jspcontainerregistry.azurecr.io/azurekeyvaulttestapi
          ports:
          - containerPort: 443
