apiVersion : apps/v1
kind: Deployment
metadata:
  name: azurekeyvaulttestapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurekeyvaulttestapi
  template:
    metadata:
      labels:
        app: azurekeyvaulttestapi 
    spec:
      containers:
        - name: azurekeyvaulttestapi 
          image: jspcontainerregistry.azurecr.io/azurekeyvaulttestapi
          ports:
          - containerPort: 443
